// 
// Decompiled by Procyon v0.5.36
// 

package com.yasoka.screenrecord.sdk.core.lasque.tusdk.modules.components;

public class ComponentActType
{
    public static long sdkComponent;
    public static long sdkLoadedComponent;
    public static long sdkSimpleCamera;
    public static long albumComponent;
    public static long albumListFragment;
    public static long albumMultipleComponent;
    public static long albumMultipleListFragment;
    public static long photoListFragment;
    public static long photoListPreviewFragment;
    public static long avatarComponent;
    public static long editComponent;
    public static long editCuterFragment;
    public static long editCuter_action_trun_left;
    public static long editCuter_action_trun_right;
    public static long editCuter_action_mirror_horizontal;
    public static long editCuter_action_mirror_vertical;
    public static long editCuter_action_ratio_orgin;
    public static long editCuter_action_ratio_9_16;
    public static long editCuter_action_ratio_3_4;
    public static long editCuter_action_ratio_2_3;
    public static long editCuter_action_ratio_1_1;
    public static long editCuter_action_ratio_3_2;
    public static long editCuter_action_ratio_4_3;
    public static long editCuter_action_ratio_16_9;
    public static long editEntryFragment;
    public static long editFilterFragment;
    public static long editTurnAndCutFragment;
    public static long editPhotoAction;
    public static long editMultipleComponent;
    public static long editMultipleFragment;
    public static long editSkinFragment;
    public static long editAdjustFragment;
    public static long editSharpnessFragment;
    public static long editApertureFragment;
    public static long editVignetteFragment;
    public static long editFilterOnlineFragment;
    public static long editSmudgeFragment;
    public static long editPaintSmudgeFragment;
    public static long editWipeAndFilterFragment;
    public static long editHolyLightFragment;
    public static long editHDRFragment;
    public static long cameraFragment;
    public static long camera_action_take_picture;
    public static long camera_action_capture_with_volume;
    public static long camera_action_faceing_back;
    public static long camera_action_faceing_front;
    public static long camera_action_flash_off;
    public static long camera_action_flash_on;
    public static long camera_action_flash_auto;
    public static long camera_action_ratio_orgin;
    public static long camera_action_ratio_9_16;
    public static long camera_action_ratio_3_4;
    public static long camera_action_ratio_2_3;
    public static long camera_action_ratio_1_1;
    public static long editStickerLocalFragment;
    public static long editStickerOnlineFragment;
    public static long editStickerFragment;
    public static long editTextFragment;
    public static long gifViewer;
    public static long image_Analysis_color;
    public static long multipleEditFragment;
    public static long cameraPreviewFragment;
    public static long getUpdatedAppAuthAction;
    public static long getAppAuthActionSuccess;
    public static long getAppAuthActionFail;
    public static long updateAppAuthActionSuccess;
    public static long updateAppAuthActionFail;
    
    static {
        ComponentActType.sdkComponent = 1L;
        ComponentActType.sdkLoadedComponent = 2L;
        ComponentActType.sdkSimpleCamera = 16L;
        ComponentActType.albumComponent = 2097152L;
        ComponentActType.albumListFragment = 2101248L;
        ComponentActType.albumMultipleComponent = 2097153L;
        ComponentActType.albumMultipleListFragment = 2101249L;
        ComponentActType.photoListFragment = 2105344L;
        ComponentActType.photoListPreviewFragment = 2105345L;
        ComponentActType.avatarComponent = 3145728L;
        ComponentActType.editComponent = 4194304L;
        ComponentActType.editCuterFragment = 4198400L;
        ComponentActType.editCuter_action_trun_left = 4198417L;
        ComponentActType.editCuter_action_trun_right = 4198418L;
        ComponentActType.editCuter_action_mirror_horizontal = 4198433L;
        ComponentActType.editCuter_action_mirror_vertical = 4198434L;
        ComponentActType.editCuter_action_ratio_orgin = 4198464L;
        ComponentActType.editCuter_action_ratio_9_16 = 4198465L;
        ComponentActType.editCuter_action_ratio_3_4 = 4198466L;
        ComponentActType.editCuter_action_ratio_2_3 = 4198467L;
        ComponentActType.editCuter_action_ratio_1_1 = 4198468L;
        ComponentActType.editCuter_action_ratio_3_2 = 4198469L;
        ComponentActType.editCuter_action_ratio_4_3 = 4198470L;
        ComponentActType.editCuter_action_ratio_16_9 = 4198471L;
        ComponentActType.editEntryFragment = 4202496L;
        ComponentActType.editFilterFragment = 4206592L;
        ComponentActType.editTurnAndCutFragment = 4210688L;
        ComponentActType.editPhotoAction = 4214784L;
        ComponentActType.editMultipleComponent = 4218880L;
        ComponentActType.editMultipleFragment = 4222976L;
        ComponentActType.editSkinFragment = 4227072L;
        ComponentActType.editAdjustFragment = 4231168L;
        ComponentActType.editSharpnessFragment = 4231424L;
        ComponentActType.editApertureFragment = 4231680L;
        ComponentActType.editVignetteFragment = 4231936L;
        ComponentActType.editFilterOnlineFragment = 4232192L;
        ComponentActType.editSmudgeFragment = 4232448L;
        ComponentActType.editPaintSmudgeFragment = 4232449L;
        ComponentActType.editWipeAndFilterFragment = 4232704L;
        ComponentActType.editHolyLightFragment = 4232960L;
        ComponentActType.editHDRFragment = 4233472L;
        ComponentActType.cameraFragment = 5242880L;
        ComponentActType.camera_action_take_picture = 5246992L;
        ComponentActType.camera_action_capture_with_volume = 5246993L;
        ComponentActType.camera_action_faceing_back = 5247009L;
        ComponentActType.camera_action_faceing_front = 5247010L;
        ComponentActType.camera_action_flash_off = 5247024L;
        ComponentActType.camera_action_flash_on = 5247025L;
        ComponentActType.camera_action_flash_auto = 5247026L;
        ComponentActType.camera_action_ratio_orgin = 5247040L;
        ComponentActType.camera_action_ratio_9_16 = 5247041L;
        ComponentActType.camera_action_ratio_3_4 = 5247042L;
        ComponentActType.camera_action_ratio_2_3 = 5247043L;
        ComponentActType.camera_action_ratio_1_1 = 5247044L;
        ComponentActType.editStickerLocalFragment = 6295552L;
        ComponentActType.editStickerOnlineFragment = 6299648L;
        ComponentActType.editStickerFragment = 6303744L;
        ComponentActType.editTextFragment = 4259840L;
        ComponentActType.gifViewer = 7340032L;
        ComponentActType.image_Analysis_color = 8388609L;
        ComponentActType.multipleEditFragment = 4233216L;
        ComponentActType.cameraPreviewFragment = 5242896L;
        ComponentActType.getUpdatedAppAuthAction = 8454144L;
        ComponentActType.getAppAuthActionSuccess = 8454146L;
        ComponentActType.getAppAuthActionFail = 8454148L;
        ComponentActType.updateAppAuthActionSuccess = 8454150L;
        ComponentActType.updateAppAuthActionFail = 8454152L;
    }
}
